# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import Field, StrictStr
from ari_async_sdk.models.channel import Channel
from ari_async_sdk.models.event import Event

class Dial(Event):
    """
    Dial
    """
    caller: Optional[Channel] = None
    dialstatus: StrictStr = Field(default=..., description="Current status of the dialing attempt to the peer.")
    dialstring: Optional[StrictStr] = Field(default=None, description="The dial string for calling the peer channel.")
    forward: Optional[StrictStr] = Field(default=None, description="Forwarding target requested by the original dialed channel.")
    forwarded: Optional[Channel] = None
    peer: Channel = Field(...)
    __properties = ["application", "timestamp", "asterisk_id", "type", "caller", "dialstatus", "dialstring", "forward", "forwarded", "peer"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Dial:
        """Create an instance of Dial from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of caller
        if self.caller:
            _dict['caller'] = self.caller.to_dict()
        # override the default output from pydantic by calling `to_dict()` of forwarded
        if self.forwarded:
            _dict['forwarded'] = self.forwarded.to_dict()
        # override the default output from pydantic by calling `to_dict()` of peer
        if self.peer:
            _dict['peer'] = self.peer.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Dial:
        """Create an instance of Dial from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Dial.parse_obj(obj)

        _obj = Dial.parse_obj({
            "application": obj.get("application"),
            "timestamp": obj.get("timestamp"),
            "asterisk_id": obj.get("asterisk_id"),
            "type": obj.get("type"),
            "caller": Channel.from_dict(obj.get("caller")) if obj.get("caller") is not None else None,
            "dialstatus": obj.get("dialstatus"),
            "dialstring": obj.get("dialstring"),
            "forward": obj.get("forward"),
            "forwarded": Channel.from_dict(obj.get("forwarded")) if obj.get("forwarded") is not None else None,
            "peer": Channel.from_dict(obj.get("peer")) if obj.get("peer") is not None else None
        })
        return _obj


