# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr

class Module(BaseModel):
    """
    Details of an Asterisk module  # noqa: E501
    """
    description: StrictStr = Field(default=..., description="The description of this module")
    name: StrictStr = Field(default=..., description="The name of this module")
    status: StrictStr = Field(default=..., description="The running status of this module")
    support_level: StrictStr = Field(default=..., description="The support state of this module")
    use_count: StrictInt = Field(default=..., description="The number of times this module is being used")
    __properties = ["description", "name", "status", "support_level", "use_count"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Module:
        """Create an instance of Module from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Module:
        """Create an instance of Module from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Module.parse_obj(obj)

        _obj = Module.parse_obj({
            "description": obj.get("description"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "support_level": obj.get("support_level"),
            "use_count": obj.get("use_count")
        })
        return _obj


