# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ari_sync_sdk.models.endpoint import Endpoint

class TestEndpoint(unittest.TestCase):
    """Endpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Endpoint:
        """Test Endpoint
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Endpoint`
        """
        model = Endpoint()
        if include_optional:
            return Endpoint(
                channel_ids = [
                    ''
                    ],
                resource = '',
                state = '',
                technology = ''
            )
        else:
            return Endpoint(
                channel_ids = [
                    ''
                    ],
                resource = '',
                technology = '',
        )
        """

    def testEndpoint(self):
        """Test Endpoint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
