# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ari_sync_sdk.models.dialplan_cep import DialplanCEP

class TestDialplanCEP(unittest.TestCase):
    """DialplanCEP unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DialplanCEP:
        """Test DialplanCEP
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DialplanCEP`
        """
        model = DialplanCEP()
        if include_optional:
            return DialplanCEP(
                app_data = '',
                app_name = '',
                context = '',
                exten = '',
                priority = 56
            )
        else:
            return DialplanCEP(
                app_data = '',
                app_name = '',
                context = '',
                exten = '',
                priority = 56,
        )
        """

    def testDialplanCEP(self):
        """Test DialplanCEP"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
