# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ari_sync_sdk.api.recordings_api import RecordingsApi


class TestRecordingsApi(unittest.TestCase):
    """RecordingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecordingsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel(self) -> None:
        """Test case for cancel

        Stop a live recording and discard it.
        """
        pass

    def test_copy_stored(self) -> None:
        """Test case for copy_stored

        Copy a stored recording.
        """
        pass

    def test_delete_stored(self) -> None:
        """Test case for delete_stored

        Delete a stored recording.
        """
        pass

    def test_get_live(self) -> None:
        """Test case for get_live

        List live recordings.
        """
        pass

    def test_get_stored(self) -> None:
        """Test case for get_stored

        Get a stored recording's details.
        """
        pass

    def test_get_stored_file(self) -> None:
        """Test case for get_stored_file

        Get the file associated with the stored recording.
        """
        pass

    def test_list_stored(self) -> None:
        """Test case for list_stored

        List recordings that are complete.
        """
        pass

    def test_muterecording(self) -> None:
        """Test case for muterecording

        Mute a live recording.
        """
        pass

    def test_pause(self) -> None:
        """Test case for pause

        Pause a live recording.
        """
        pass

    def test_stoprecording(self) -> None:
        """Test case for stoprecording

        Stop a live recording and store it.
        """
        pass

    def test_unmuterecording(self) -> None:
        """Test case for unmuterecording

        Unmute a live recording.
        """
        pass

    def test_unpause(self) -> None:
        """Test case for unpause

        Unpause a live recording.
        """
        pass


if __name__ == '__main__':
    unittest.main()
