# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ari_sync_sdk.api.endpoints_api import EndpointsApi


class TestEndpointsApi(unittest.TestCase):
    """EndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_getendpoint(self) -> None:
        """Test case for getendpoint

        Details for an endpoint.
        """
        pass

    def test_list_by_tech(self) -> None:
        """Test case for list_by_tech

        List available endoints for a given endpoint technology.
        """
        pass

    def test_listendpoints(self) -> None:
        """Test case for listendpoints

        List all endpoints.
        """
        pass

    def test_send_message(self) -> None:
        """Test case for send_message

        Send a message to some technology URI or endpoint.
        """
        pass

    def test_send_message_to_endpoint(self) -> None:
        """Test case for send_message_to_endpoint

        Send a message to some endpoint in a technology.
        """
        pass


if __name__ == '__main__':
    unittest.main()
