# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ari_sync_sdk.models.peer_status_change import PeerStatusChange

class TestPeerStatusChange(unittest.TestCase):
    """PeerStatusChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PeerStatusChange:
        """Test PeerStatusChange
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeerStatusChange`
        """
        model = PeerStatusChange()
        if include_optional:
            return PeerStatusChange(
                endpoint = ari_sync_sdk.models.endpoint.Endpoint(
                    channel_ids = [
                        ''
                        ], 
                    resource = '', 
                    state = '', 
                    technology = '', ),
                peer = ari_sync_sdk.models.peer.Peer(
                    address = '', 
                    cause = '', 
                    peer_status = '', 
                    port = '', 
                    time = '', )
            )
        else:
            return PeerStatusChange(
                endpoint = ari_sync_sdk.models.endpoint.Endpoint(
                    channel_ids = [
                        ''
                        ], 
                    resource = '', 
                    state = '', 
                    technology = '', ),
                peer = ari_sync_sdk.models.peer.Peer(
                    address = '', 
                    cause = '', 
                    peer_status = '', 
                    port = '', 
                    time = '', ),
        )
        """

    def testPeerStatusChange(self):
        """Test PeerStatusChange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
