# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from ari_sync_sdk.models.set_id import SetId
from typing import Optional, Set
from typing_extensions import Self

class ConfigInfo(BaseModel):
    """
    Info about Asterisk configuration
    """ # noqa: E501
    default_language: StrictStr = Field(description="Default language for media playback.")
    max_channels: Optional[StrictInt] = Field(default=None, description="Maximum number of simultaneous channels.")
    max_load: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Maximum load avg on system.")
    max_open_files: Optional[StrictInt] = Field(default=None, description="Maximum number of open file handles (files, sockets).")
    name: StrictStr = Field(description="Asterisk system name.")
    setid: SetId
    __properties: ClassVar[List[str]] = ["default_language", "max_channels", "max_load", "max_open_files", "name", "setid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of setid
        if self.setid:
            _dict['setid'] = self.setid.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "default_language": obj.get("default_language"),
            "max_channels": obj.get("max_channels"),
            "max_load": obj.get("max_load"),
            "max_open_files": obj.get("max_open_files"),
            "name": obj.get("name"),
            "setid": SetId.from_dict(obj["setid"]) if obj.get("setid") is not None else None
        })
        return _obj


