# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class LiveRecording(BaseModel):
    """
    A recording that is in progress
    """ # noqa: E501
    cause: Optional[StrictStr] = Field(default=None, description="Cause for recording failure if failed")
    duration: Optional[StrictInt] = Field(default=None, description="Duration in seconds of the recording")
    format: StrictStr = Field(description="Recording format (wav, gsm, etc.)")
    name: StrictStr = Field(description="Base name for the recording")
    silence_duration: Optional[StrictInt] = Field(default=None, description="Duration of silence, in seconds, detected in the recording. This is only available if the recording was initiated with a non-zero maxSilenceSeconds.")
    state: StrictStr
    talking_duration: Optional[StrictInt] = Field(default=None, description="Duration of talking, in seconds, detected in the recording. This is only available if the recording was initiated with a non-zero maxSilenceSeconds.")
    target_uri: StrictStr = Field(description="URI for the channel or bridge being recorded")
    __properties: ClassVar[List[str]] = ["cause", "duration", "format", "name", "silence_duration", "state", "talking_duration", "target_uri"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LiveRecording from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LiveRecording from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cause": obj.get("cause"),
            "duration": obj.get("duration"),
            "format": obj.get("format"),
            "name": obj.get("name"),
            "silence_duration": obj.get("silence_duration"),
            "state": obj.get("state"),
            "talking_duration": obj.get("talking_duration"),
            "target_uri": obj.get("target_uri")
        })
        return _obj


