# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from ari_async_sdk.models.base_model import Model
from ari_async_sdk.models.build_info import BuildInfo
from ari_async_sdk.models.config_info import ConfigInfo
from ari_async_sdk.models.status_info import StatusInfo
from ari_async_sdk.models.system_info import SystemInfo
from ari_async_sdk import util


class AsteriskInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, build: BuildInfo=None, config: ConfigInfo=None, status: StatusInfo=None, system: SystemInfo=None):
        """AsteriskInfo - a model defined in OpenAPI

        :param build: The build of this AsteriskInfo.
        :param config: The config of this AsteriskInfo.
        :param status: The status of this AsteriskInfo.
        :param system: The system of this AsteriskInfo.
        """
        self.openapi_types = {
            'build': BuildInfo,
            'config': ConfigInfo,
            'status': StatusInfo,
            'system': SystemInfo
        }

        self.attribute_map = {
            'build': 'build',
            'config': 'config',
            'status': 'status',
            'system': 'system'
        }

        self._build = build
        self._config = config
        self._status = status
        self._system = system

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AsteriskInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AsteriskInfo of this AsteriskInfo.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def build(self):
        """Gets the build of this AsteriskInfo.


        :return: The build of this AsteriskInfo.
        :rtype: BuildInfo
        """
        return self._build

    @build.setter
    def build(self, build):
        """Sets the build of this AsteriskInfo.


        :param build: The build of this AsteriskInfo.
        :type build: BuildInfo
        """

        self._build = build

    @property
    def config(self):
        """Gets the config of this AsteriskInfo.


        :return: The config of this AsteriskInfo.
        :rtype: ConfigInfo
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this AsteriskInfo.


        :param config: The config of this AsteriskInfo.
        :type config: ConfigInfo
        """

        self._config = config

    @property
    def status(self):
        """Gets the status of this AsteriskInfo.


        :return: The status of this AsteriskInfo.
        :rtype: StatusInfo
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this AsteriskInfo.


        :param status: The status of this AsteriskInfo.
        :type status: StatusInfo
        """

        self._status = status

    @property
    def system(self):
        """Gets the system of this AsteriskInfo.


        :return: The system of this AsteriskInfo.
        :rtype: SystemInfo
        """
        return self._system

    @system.setter
    def system(self, system):
        """Sets the system of this AsteriskInfo.


        :param system: The system of this AsteriskInfo.
        :type system: SystemInfo
        """

        self._system = system
