# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from ari_async_sdk.models.base_model import Model
from ari_async_sdk.models.bridge import Bridge
from ari_async_sdk.models.event import Event
from ari_async_sdk import util


class BridgeMerged(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, application: str=None, timestamp: date=None, asterisk_id: str=None, type: str=None, bridge: Bridge=None, bridge_from: Bridge=None):
        """BridgeMerged - a model defined in OpenAPI

        :param application: The application of this BridgeMerged.
        :param timestamp: The timestamp of this BridgeMerged.
        :param asterisk_id: The asterisk_id of this BridgeMerged.
        :param type: The type of this BridgeMerged.
        :param bridge: The bridge of this BridgeMerged.
        :param bridge_from: The bridge_from of this BridgeMerged.
        """
        self.openapi_types = {
            'application': str,
            'timestamp': date,
            'asterisk_id': str,
            'type': str,
            'bridge': Bridge,
            'bridge_from': Bridge
        }

        self.attribute_map = {
            'application': 'application',
            'timestamp': 'timestamp',
            'asterisk_id': 'asterisk_id',
            'type': 'type',
            'bridge': 'bridge',
            'bridge_from': 'bridge_from'
        }

        self._application = application
        self._timestamp = timestamp
        self._asterisk_id = asterisk_id
        self._type = type
        self._bridge = bridge
        self._bridge_from = bridge_from

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BridgeMerged':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BridgeMerged of this BridgeMerged.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def application(self):
        """Gets the application of this BridgeMerged.

        Name of the application receiving the event.

        :return: The application of this BridgeMerged.
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this BridgeMerged.

        Name of the application receiving the event.

        :param application: The application of this BridgeMerged.
        :type application: str
        """
        if application is None:
            raise ValueError("Invalid value for `application`, must not be `None`")

        self._application = application

    @property
    def timestamp(self):
        """Gets the timestamp of this BridgeMerged.

        Time at which this event was created.

        :return: The timestamp of this BridgeMerged.
        :rtype: date
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this BridgeMerged.

        Time at which this event was created.

        :param timestamp: The timestamp of this BridgeMerged.
        :type timestamp: date
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")

        self._timestamp = timestamp

    @property
    def asterisk_id(self):
        """Gets the asterisk_id of this BridgeMerged.

        The unique ID for the Asterisk instance that raised this event.

        :return: The asterisk_id of this BridgeMerged.
        :rtype: str
        """
        return self._asterisk_id

    @asterisk_id.setter
    def asterisk_id(self, asterisk_id):
        """Sets the asterisk_id of this BridgeMerged.

        The unique ID for the Asterisk instance that raised this event.

        :param asterisk_id: The asterisk_id of this BridgeMerged.
        :type asterisk_id: str
        """

        self._asterisk_id = asterisk_id

    @property
    def type(self):
        """Gets the type of this BridgeMerged.

        Indicates the type of this message.

        :return: The type of this BridgeMerged.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this BridgeMerged.

        Indicates the type of this message.

        :param type: The type of this BridgeMerged.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def bridge(self):
        """Gets the bridge of this BridgeMerged.


        :return: The bridge of this BridgeMerged.
        :rtype: Bridge
        """
        return self._bridge

    @bridge.setter
    def bridge(self, bridge):
        """Sets the bridge of this BridgeMerged.


        :param bridge: The bridge of this BridgeMerged.
        :type bridge: Bridge
        """
        if bridge is None:
            raise ValueError("Invalid value for `bridge`, must not be `None`")

        self._bridge = bridge

    @property
    def bridge_from(self):
        """Gets the bridge_from of this BridgeMerged.


        :return: The bridge_from of this BridgeMerged.
        :rtype: Bridge
        """
        return self._bridge_from

    @bridge_from.setter
    def bridge_from(self, bridge_from):
        """Sets the bridge_from of this BridgeMerged.


        :param bridge_from: The bridge_from of this BridgeMerged.
        :type bridge_from: Bridge
        """
        if bridge_from is None:
            raise ValueError("Invalid value for `bridge_from`, must not be `None`")

        self._bridge_from = bridge_from
