# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from ari_async_sdk.models.base_model import Model
from ari_async_sdk.models.bridge import Bridge
from ari_async_sdk.models.channel import Channel
from ari_async_sdk.models.endpoint import Endpoint
from ari_async_sdk.models.event import Event
from ari_async_sdk import util


class ChannelUserevent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, application: str=None, timestamp: date=None, asterisk_id: str=None, type: str=None, bridge: Bridge=None, channel: Channel=None, endpoint: Endpoint=None, eventname: str=None, userevent: object=None):
        """ChannelUserevent - a model defined in OpenAPI

        :param application: The application of this ChannelUserevent.
        :param timestamp: The timestamp of this ChannelUserevent.
        :param asterisk_id: The asterisk_id of this ChannelUserevent.
        :param type: The type of this ChannelUserevent.
        :param bridge: The bridge of this ChannelUserevent.
        :param channel: The channel of this ChannelUserevent.
        :param endpoint: The endpoint of this ChannelUserevent.
        :param eventname: The eventname of this ChannelUserevent.
        :param userevent: The userevent of this ChannelUserevent.
        """
        self.openapi_types = {
            'application': str,
            'timestamp': date,
            'asterisk_id': str,
            'type': str,
            'bridge': Bridge,
            'channel': Channel,
            'endpoint': Endpoint,
            'eventname': str,
            'userevent': object
        }

        self.attribute_map = {
            'application': 'application',
            'timestamp': 'timestamp',
            'asterisk_id': 'asterisk_id',
            'type': 'type',
            'bridge': 'bridge',
            'channel': 'channel',
            'endpoint': 'endpoint',
            'eventname': 'eventname',
            'userevent': 'userevent'
        }

        self._application = application
        self._timestamp = timestamp
        self._asterisk_id = asterisk_id
        self._type = type
        self._bridge = bridge
        self._channel = channel
        self._endpoint = endpoint
        self._eventname = eventname
        self._userevent = userevent

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ChannelUserevent':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ChannelUserevent of this ChannelUserevent.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def application(self):
        """Gets the application of this ChannelUserevent.

        Name of the application receiving the event.

        :return: The application of this ChannelUserevent.
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this ChannelUserevent.

        Name of the application receiving the event.

        :param application: The application of this ChannelUserevent.
        :type application: str
        """
        if application is None:
            raise ValueError("Invalid value for `application`, must not be `None`")

        self._application = application

    @property
    def timestamp(self):
        """Gets the timestamp of this ChannelUserevent.

        Time at which this event was created.

        :return: The timestamp of this ChannelUserevent.
        :rtype: date
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ChannelUserevent.

        Time at which this event was created.

        :param timestamp: The timestamp of this ChannelUserevent.
        :type timestamp: date
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")

        self._timestamp = timestamp

    @property
    def asterisk_id(self):
        """Gets the asterisk_id of this ChannelUserevent.

        The unique ID for the Asterisk instance that raised this event.

        :return: The asterisk_id of this ChannelUserevent.
        :rtype: str
        """
        return self._asterisk_id

    @asterisk_id.setter
    def asterisk_id(self, asterisk_id):
        """Sets the asterisk_id of this ChannelUserevent.

        The unique ID for the Asterisk instance that raised this event.

        :param asterisk_id: The asterisk_id of this ChannelUserevent.
        :type asterisk_id: str
        """

        self._asterisk_id = asterisk_id

    @property
    def type(self):
        """Gets the type of this ChannelUserevent.

        Indicates the type of this message.

        :return: The type of this ChannelUserevent.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ChannelUserevent.

        Indicates the type of this message.

        :param type: The type of this ChannelUserevent.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def bridge(self):
        """Gets the bridge of this ChannelUserevent.


        :return: The bridge of this ChannelUserevent.
        :rtype: Bridge
        """
        return self._bridge

    @bridge.setter
    def bridge(self, bridge):
        """Sets the bridge of this ChannelUserevent.


        :param bridge: The bridge of this ChannelUserevent.
        :type bridge: Bridge
        """

        self._bridge = bridge

    @property
    def channel(self):
        """Gets the channel of this ChannelUserevent.


        :return: The channel of this ChannelUserevent.
        :rtype: Channel
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this ChannelUserevent.


        :param channel: The channel of this ChannelUserevent.
        :type channel: Channel
        """

        self._channel = channel

    @property
    def endpoint(self):
        """Gets the endpoint of this ChannelUserevent.


        :return: The endpoint of this ChannelUserevent.
        :rtype: Endpoint
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint):
        """Sets the endpoint of this ChannelUserevent.


        :param endpoint: The endpoint of this ChannelUserevent.
        :type endpoint: Endpoint
        """

        self._endpoint = endpoint

    @property
    def eventname(self):
        """Gets the eventname of this ChannelUserevent.

        The name of the user event.

        :return: The eventname of this ChannelUserevent.
        :rtype: str
        """
        return self._eventname

    @eventname.setter
    def eventname(self, eventname):
        """Sets the eventname of this ChannelUserevent.

        The name of the user event.

        :param eventname: The eventname of this ChannelUserevent.
        :type eventname: str
        """
        if eventname is None:
            raise ValueError("Invalid value for `eventname`, must not be `None`")

        self._eventname = eventname

    @property
    def userevent(self):
        """Gets the userevent of this ChannelUserevent.

        Custom Userevent data

        :return: The userevent of this ChannelUserevent.
        :rtype: object
        """
        return self._userevent

    @userevent.setter
    def userevent(self, userevent):
        """Sets the userevent of this ChannelUserevent.

        Custom Userevent data

        :param userevent: The userevent of this ChannelUserevent.
        :type userevent: object
        """
        if userevent is None:
            raise ValueError("Invalid value for `userevent`, must not be `None`")

        self._userevent = userevent
