# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from ari_async_sdk.models.base_model import Model
from ari_async_sdk.models.channel import Channel
from ari_async_sdk.models.event import Event
from ari_async_sdk import util


class ChannelVarset(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, application: str=None, timestamp: date=None, asterisk_id: str=None, type: str=None, channel: Channel=None, value: str=None, variable: str=None):
        """ChannelVarset - a model defined in OpenAPI

        :param application: The application of this ChannelVarset.
        :param timestamp: The timestamp of this ChannelVarset.
        :param asterisk_id: The asterisk_id of this ChannelVarset.
        :param type: The type of this ChannelVarset.
        :param channel: The channel of this ChannelVarset.
        :param value: The value of this ChannelVarset.
        :param variable: The variable of this ChannelVarset.
        """
        self.openapi_types = {
            'application': str,
            'timestamp': date,
            'asterisk_id': str,
            'type': str,
            'channel': Channel,
            'value': str,
            'variable': str
        }

        self.attribute_map = {
            'application': 'application',
            'timestamp': 'timestamp',
            'asterisk_id': 'asterisk_id',
            'type': 'type',
            'channel': 'channel',
            'value': 'value',
            'variable': 'variable'
        }

        self._application = application
        self._timestamp = timestamp
        self._asterisk_id = asterisk_id
        self._type = type
        self._channel = channel
        self._value = value
        self._variable = variable

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ChannelVarset':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ChannelVarset of this ChannelVarset.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def application(self):
        """Gets the application of this ChannelVarset.

        Name of the application receiving the event.

        :return: The application of this ChannelVarset.
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this ChannelVarset.

        Name of the application receiving the event.

        :param application: The application of this ChannelVarset.
        :type application: str
        """
        if application is None:
            raise ValueError("Invalid value for `application`, must not be `None`")

        self._application = application

    @property
    def timestamp(self):
        """Gets the timestamp of this ChannelVarset.

        Time at which this event was created.

        :return: The timestamp of this ChannelVarset.
        :rtype: date
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ChannelVarset.

        Time at which this event was created.

        :param timestamp: The timestamp of this ChannelVarset.
        :type timestamp: date
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")

        self._timestamp = timestamp

    @property
    def asterisk_id(self):
        """Gets the asterisk_id of this ChannelVarset.

        The unique ID for the Asterisk instance that raised this event.

        :return: The asterisk_id of this ChannelVarset.
        :rtype: str
        """
        return self._asterisk_id

    @asterisk_id.setter
    def asterisk_id(self, asterisk_id):
        """Sets the asterisk_id of this ChannelVarset.

        The unique ID for the Asterisk instance that raised this event.

        :param asterisk_id: The asterisk_id of this ChannelVarset.
        :type asterisk_id: str
        """

        self._asterisk_id = asterisk_id

    @property
    def type(self):
        """Gets the type of this ChannelVarset.

        Indicates the type of this message.

        :return: The type of this ChannelVarset.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ChannelVarset.

        Indicates the type of this message.

        :param type: The type of this ChannelVarset.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def channel(self):
        """Gets the channel of this ChannelVarset.


        :return: The channel of this ChannelVarset.
        :rtype: Channel
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this ChannelVarset.


        :param channel: The channel of this ChannelVarset.
        :type channel: Channel
        """

        self._channel = channel

    @property
    def value(self):
        """Gets the value of this ChannelVarset.

        The new value of the variable.

        :return: The value of this ChannelVarset.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ChannelVarset.

        The new value of the variable.

        :param value: The value of this ChannelVarset.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")

        self._value = value

    @property
    def variable(self):
        """Gets the variable of this ChannelVarset.

        The variable that changed.

        :return: The variable of this ChannelVarset.
        :rtype: str
        """
        return self._variable

    @variable.setter
    def variable(self, variable):
        """Sets the variable of this ChannelVarset.

        The variable that changed.

        :param variable: The variable of this ChannelVarset.
        :type variable: str
        """
        if variable is None:
            raise ValueError("Invalid value for `variable`, must not be `None`")

        self._variable = variable
