# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from ari_async_sdk.models.base_model import Model
from ari_async_sdk.models.device_state import DeviceState
from ari_async_sdk.models.event import Event
from ari_async_sdk import util


class DeviceStateChanged(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, application: str=None, timestamp: date=None, asterisk_id: str=None, type: str=None, device_state: DeviceState=None):
        """DeviceStateChanged - a model defined in OpenAPI

        :param application: The application of this DeviceStateChanged.
        :param timestamp: The timestamp of this DeviceStateChanged.
        :param asterisk_id: The asterisk_id of this DeviceStateChanged.
        :param type: The type of this DeviceStateChanged.
        :param device_state: The device_state of this DeviceStateChanged.
        """
        self.openapi_types = {
            'application': str,
            'timestamp': date,
            'asterisk_id': str,
            'type': str,
            'device_state': DeviceState
        }

        self.attribute_map = {
            'application': 'application',
            'timestamp': 'timestamp',
            'asterisk_id': 'asterisk_id',
            'type': 'type',
            'device_state': 'device_state'
        }

        self._application = application
        self._timestamp = timestamp
        self._asterisk_id = asterisk_id
        self._type = type
        self._device_state = device_state

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DeviceStateChanged':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The DeviceStateChanged of this DeviceStateChanged.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def application(self):
        """Gets the application of this DeviceStateChanged.

        Name of the application receiving the event.

        :return: The application of this DeviceStateChanged.
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this DeviceStateChanged.

        Name of the application receiving the event.

        :param application: The application of this DeviceStateChanged.
        :type application: str
        """
        if application is None:
            raise ValueError("Invalid value for `application`, must not be `None`")

        self._application = application

    @property
    def timestamp(self):
        """Gets the timestamp of this DeviceStateChanged.

        Time at which this event was created.

        :return: The timestamp of this DeviceStateChanged.
        :rtype: date
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this DeviceStateChanged.

        Time at which this event was created.

        :param timestamp: The timestamp of this DeviceStateChanged.
        :type timestamp: date
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")

        self._timestamp = timestamp

    @property
    def asterisk_id(self):
        """Gets the asterisk_id of this DeviceStateChanged.

        The unique ID for the Asterisk instance that raised this event.

        :return: The asterisk_id of this DeviceStateChanged.
        :rtype: str
        """
        return self._asterisk_id

    @asterisk_id.setter
    def asterisk_id(self, asterisk_id):
        """Sets the asterisk_id of this DeviceStateChanged.

        The unique ID for the Asterisk instance that raised this event.

        :param asterisk_id: The asterisk_id of this DeviceStateChanged.
        :type asterisk_id: str
        """

        self._asterisk_id = asterisk_id

    @property
    def type(self):
        """Gets the type of this DeviceStateChanged.

        Indicates the type of this message.

        :return: The type of this DeviceStateChanged.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DeviceStateChanged.

        Indicates the type of this message.

        :param type: The type of this DeviceStateChanged.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def device_state(self):
        """Gets the device_state of this DeviceStateChanged.


        :return: The device_state of this DeviceStateChanged.
        :rtype: DeviceState
        """
        return self._device_state

    @device_state.setter
    def device_state(self, device_state):
        """Sets the device_state of this DeviceStateChanged.


        :param device_state: The device_state of this DeviceStateChanged.
        :type device_state: DeviceState
        """
        if device_state is None:
            raise ValueError("Invalid value for `device_state`, must not be `None`")

        self._device_state = device_state
