# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from ari_async_sdk.models.base_model import Model
from ari_async_sdk.models.message import Message
from ari_async_sdk import util


class Event(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, asterisk_id: str=None, type: str=None, application: str=None, timestamp: date=None):
        """Event - a model defined in OpenAPI

        :param asterisk_id: The asterisk_id of this Event.
        :param type: The type of this Event.
        :param application: The application of this Event.
        :param timestamp: The timestamp of this Event.
        """
        self.openapi_types = {
            'asterisk_id': str,
            'type': str,
            'application': str,
            'timestamp': date
        }

        self.attribute_map = {
            'asterisk_id': 'asterisk_id',
            'type': 'type',
            'application': 'application',
            'timestamp': 'timestamp'
        }

        self._asterisk_id = asterisk_id
        self._type = type
        self._application = application
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Event':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Event of this Event.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def asterisk_id(self):
        """Gets the asterisk_id of this Event.

        The unique ID for the Asterisk instance that raised this event.

        :return: The asterisk_id of this Event.
        :rtype: str
        """
        return self._asterisk_id

    @asterisk_id.setter
    def asterisk_id(self, asterisk_id):
        """Sets the asterisk_id of this Event.

        The unique ID for the Asterisk instance that raised this event.

        :param asterisk_id: The asterisk_id of this Event.
        :type asterisk_id: str
        """

        self._asterisk_id = asterisk_id

    @property
    def type(self):
        """Gets the type of this Event.

        Indicates the type of this message.

        :return: The type of this Event.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Event.

        Indicates the type of this message.

        :param type: The type of this Event.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def application(self):
        """Gets the application of this Event.

        Name of the application receiving the event.

        :return: The application of this Event.
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this Event.

        Name of the application receiving the event.

        :param application: The application of this Event.
        :type application: str
        """
        if application is None:
            raise ValueError("Invalid value for `application`, must not be `None`")

        self._application = application

    @property
    def timestamp(self):
        """Gets the timestamp of this Event.

        Time at which this event was created.

        :return: The timestamp of this Event.
        :rtype: date
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Event.

        Time at which this event was created.

        :param timestamp: The timestamp of this Event.
        :type timestamp: date
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")

        self._timestamp = timestamp
