# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from ari_async_sdk.models.base_model import Model
from ari_async_sdk.models.event import Event
from ari_async_sdk.models.live_recording import LiveRecording
from ari_async_sdk import util


class RecordingStarted(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, application: str=None, timestamp: date=None, asterisk_id: str=None, type: str=None, recording: LiveRecording=None):
        """RecordingStarted - a model defined in OpenAPI

        :param application: The application of this RecordingStarted.
        :param timestamp: The timestamp of this RecordingStarted.
        :param asterisk_id: The asterisk_id of this RecordingStarted.
        :param type: The type of this RecordingStarted.
        :param recording: The recording of this RecordingStarted.
        """
        self.openapi_types = {
            'application': str,
            'timestamp': date,
            'asterisk_id': str,
            'type': str,
            'recording': LiveRecording
        }

        self.attribute_map = {
            'application': 'application',
            'timestamp': 'timestamp',
            'asterisk_id': 'asterisk_id',
            'type': 'type',
            'recording': 'recording'
        }

        self._application = application
        self._timestamp = timestamp
        self._asterisk_id = asterisk_id
        self._type = type
        self._recording = recording

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RecordingStarted':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RecordingStarted of this RecordingStarted.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def application(self):
        """Gets the application of this RecordingStarted.

        Name of the application receiving the event.

        :return: The application of this RecordingStarted.
        :rtype: str
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this RecordingStarted.

        Name of the application receiving the event.

        :param application: The application of this RecordingStarted.
        :type application: str
        """
        if application is None:
            raise ValueError("Invalid value for `application`, must not be `None`")

        self._application = application

    @property
    def timestamp(self):
        """Gets the timestamp of this RecordingStarted.

        Time at which this event was created.

        :return: The timestamp of this RecordingStarted.
        :rtype: date
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this RecordingStarted.

        Time at which this event was created.

        :param timestamp: The timestamp of this RecordingStarted.
        :type timestamp: date
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")

        self._timestamp = timestamp

    @property
    def asterisk_id(self):
        """Gets the asterisk_id of this RecordingStarted.

        The unique ID for the Asterisk instance that raised this event.

        :return: The asterisk_id of this RecordingStarted.
        :rtype: str
        """
        return self._asterisk_id

    @asterisk_id.setter
    def asterisk_id(self, asterisk_id):
        """Sets the asterisk_id of this RecordingStarted.

        The unique ID for the Asterisk instance that raised this event.

        :param asterisk_id: The asterisk_id of this RecordingStarted.
        :type asterisk_id: str
        """

        self._asterisk_id = asterisk_id

    @property
    def type(self):
        """Gets the type of this RecordingStarted.

        Indicates the type of this message.

        :return: The type of this RecordingStarted.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RecordingStarted.

        Indicates the type of this message.

        :param type: The type of this RecordingStarted.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def recording(self):
        """Gets the recording of this RecordingStarted.


        :return: The recording of this RecordingStarted.
        :rtype: LiveRecording
        """
        return self._recording

    @recording.setter
    def recording(self, recording):
        """Sets the recording of this RecordingStarted.


        :param recording: The recording of this RecordingStarted.
        :type recording: LiveRecording
        """
        if recording is None:
            raise ValueError("Invalid value for `recording`, must not be `None`")

        self._recording = recording
