# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ari_async_sdk.api.applications_api import ApplicationsApi  # noqa: E501


class TestApplicationsApi(unittest.IsolatedAsyncioTestCase):
    """ApplicationsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ApplicationsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_filter(self) -> None:
        """Test case for filter

        Filter application events types.  # noqa: E501
        """
        pass

    async def test_get(self) -> None:
        """Test case for get

        Get details of an application.  # noqa: E501
        """
        pass

    async def test_list(self) -> None:
        """Test case for list

        List all applications.  # noqa: E501
        """
        pass

    async def test_subscribe(self) -> None:
        """Test case for subscribe

        Subscribe an application to a event source.  # noqa: E501
        """
        pass

    async def test_unsubscribe(self) -> None:
        """Test case for unsubscribe

        Unsubscribe an application from an event source.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
