# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ari_sync_sdk.models.build_info import BuildInfo  # noqa: E501

class TestBuildInfo(unittest.TestCase):
    """BuildInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuildInfo:
        """Test BuildInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuildInfo`
        """
        model = BuildInfo()  # noqa: E501
        if include_optional:
            return BuildInfo(
                var_date = '',
                kernel = '',
                machine = '',
                options = '',
                os = '',
                user = ''
            )
        else:
            return BuildInfo(
                var_date = '',
                kernel = '',
                machine = '',
                options = '',
                os = '',
                user = '',
        )
        """

    def testBuildInfo(self):
        """Test BuildInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
