# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ari_async_sdk.api.mailboxes_api import MailboxesApi  # noqa: E501


class TestMailboxesApi(unittest.IsolatedAsyncioTestCase):
    """MailboxesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = MailboxesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_deletemailbox(self) -> None:
        """Test case for deletemailbox

        Destroy a mailbox.  # noqa: E501
        """
        pass

    async def test_getmailbox(self) -> None:
        """Test case for getmailbox

        Retrieve the current state of a mailbox.  # noqa: E501
        """
        pass

    async def test_listmailboxes(self) -> None:
        """Test case for listmailboxes

        List all mailboxes.  # noqa: E501
        """
        pass

    async def test_updatemailbox(self) -> None:
        """Test case for updatemailbox

        Change the state of a mailbox. (Note - implicitly creates the mailbox).  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
