# coding: utf-8

"""
    Asterisk ARI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ari_async_sdk.api.events_api import EventsApi  # noqa: E501


class TestEventsApi(unittest.IsolatedAsyncioTestCase):
    """EventsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = EventsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_event_websocket(self) -> None:
        """Test case for event_websocket

        WebSocket connection for events.  # noqa: E501
        """
        pass

    async def test_user_event(self) -> None:
        """Test case for user_event

        Generate a user event.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
